theme: jekyll-theme-minimal
title: <img width="20%" height="20%" src="https://raw.githubusercontent.com/yumm-b612/moji.py/main/utils/assets/moji/moji_hd.png"/> Sir Moji of Honkburg
description: The whoelesome Linux bot
